//finished


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ems;


import EmployeeDoesntExist;
import static java.lang.Double.parseDouble;

/**
 *
 * @author 559544
 */
public class AddEmployee extends javax.swing.JFrame {
    
    MyHashTable hashTable;
    String gender;
    
    
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee(MyHashTable hashTable) {
        this.hashTable = hashTable;
        
        initComponents();
        hourlyWage.setVisible(false);
        weeksPerYear.setVisible(false);
        hourlyWageBox.setVisible(false);
        weeksPerYearBox.setVisible(false);
        annualSalary.setVisible(false);
        annualSalaryBox.setVisible(false);
        
        addEmployeeTitle.setEditable(false);

    }

    public AddEmployee() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        addEmployeeTitle = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lastNameBox = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        firstNameBox = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        emplyeeNumberBox = new javax.swing.JTextPane();
        firstNameText = new javax.swing.JLabel();
        lastNameText = new javax.swing.JLabel();
        workLocation = new javax.swing.JLabel();
        fullTimeSelect = new javax.swing.JCheckBox();
        partTimeSelect = new javax.swing.JCheckBox();
        employeeNumber = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        deductionRate = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        deductionRateBox = new javax.swing.JTextPane();
        hourlyWage = new javax.swing.JLabel();
        weeksPerYear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hourlyWageBox = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        weeksPerYearBox = new javax.swing.JTextPane();
        chooseOneOption = new javax.swing.JLabel();
        hoursPerWeek = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        hoursPerWeekBox = new javax.swing.JTextPane();
        annualSalary = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        annualSalaryBox = new javax.swing.JTextPane();
        maleSelected = new javax.swing.JCheckBox();
        femaleSelected = new javax.swing.JCheckBox();
        otherSelected = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        workLocationBox = new javax.swing.JTextPane();

        jScrollPane4.setViewportView(jTextPane4);

        jScrollPane7.setViewportView(jTextPane7);

        jScrollPane9.setViewportView(jTextPane9);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addEmployeeTitle.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        addEmployeeTitle.setText("Add Employee");
        addEmployeeTitle.setBorder(new javax.swing.border.SoftBevelBorder(0));
        addEmployeeTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeTitleActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitButtonMousePressed(evt);
            }
        });

        jScrollPane2.setViewportView(lastNameBox);

        jScrollPane3.setViewportView(firstNameBox);

        emplyeeNumberBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emplyeeNumberBoxKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(emplyeeNumberBox);

        firstNameText.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        firstNameText.setText("First Name");

        lastNameText.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        lastNameText.setText("Last Name");

        workLocation.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        workLocation.setText("Work Location");

        fullTimeSelect.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        fullTimeSelect.setText("Full Time");
        fullTimeSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fullTimeSelectMousePressed(evt);
            }
        });

        partTimeSelect.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        partTimeSelect.setText("Part Time");
        partTimeSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                partTimeSelectMousePressed(evt);
            }
        });
        partTimeSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeSelectActionPerformed(evt);
            }
        });

        employeeNumber.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        employeeNumber.setText("Employee Number");

        Gender.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        Gender.setText("Gender");

        deductionRate.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        deductionRate.setText("Deduction Rate");

        deductionRateBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deductionRateBoxKeyTyped(evt);
            }
        });
        jScrollPane11.setViewportView(deductionRateBox);

        hourlyWage.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        hourlyWage.setText("Hourly Wage");

        weeksPerYear.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        weeksPerYear.setText("Weeks Per Year");

        hourlyWageBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hourlyWageBoxKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(hourlyWageBox);

        weeksPerYearBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weeksPerYearBoxKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(weeksPerYearBox);

        chooseOneOption.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chooseOneOption.setText("Choose One Option");

        hoursPerWeek.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        hoursPerWeek.setText("Hours Per Week");

        hoursPerWeekBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hoursPerWeekBoxKeyTyped(evt);
            }
        });
        jScrollPane12.setViewportView(hoursPerWeekBox);

        annualSalary.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        annualSalary.setText("Annual Salary");

        jScrollPane13.setViewportView(annualSalaryBox);

        maleSelected.setText("Male");
        maleSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleSelectedActionPerformed(evt);
            }
        });

        femaleSelected.setText("Female");

        otherSelected.setText("Other");

        jScrollPane8.setViewportView(workLocationBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(maleSelected)
                            .addGap(18, 18, 18)
                            .addComponent(femaleSelected)
                            .addGap(18, 18, 18)
                            .addComponent(otherSelected))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(employeeNumber)
                                        .addComponent(workLocation))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNameText)
                                        .addComponent(lastNameText))
                                    .addGap(43, 43, 43)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(Gender)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partTimeSelect)
                            .addComponent(fullTimeSelect))
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hoursPerWeek)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(weeksPerYear)
                                            .addComponent(hourlyWage)
                                            .addComponent(annualSalary)
                                            .addComponent(deductionRate, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                            .addComponent(jScrollPane13)
                                            .addComponent(jScrollPane11)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(chooseOneOption)))
                                .addContainerGap(24, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addEmployeeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameText))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameText)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chooseOneOption)
                        .addGap(18, 18, 18)
                        .addComponent(fullTimeSelect)
                        .addGap(18, 18, 18)
                        .addComponent(partTimeSelect)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(annualSalary)
                                .addGap(7, 7, 7)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hourlyWage)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoursPerWeek)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workLocation))
                        .addGap(18, 18, 18)
                        .addComponent(Gender)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(femaleSelected)
                            .addComponent(otherSelected)
                            .addComponent(maleSelected))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(weeksPerYear)
                                .addGap(20, 20, 20)
                                .addComponent(deductionRate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeeTitleActionPerformed

    private void partTimeSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partTimeSelectActionPerformed

    private void partTimeSelectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partTimeSelectMousePressed
        // TODO add your handling code here:
        hourlyWage.setVisible(true);
        weeksPerYear.setVisible(true);
        hourlyWageBox.setVisible(true);
        weeksPerYearBox.setVisible(true);
        hoursPerWeek.setVisible(true);
        hoursPerWeekBox.setVisible(true);
        annualSalary.setVisible(false);
        annualSalaryBox.setVisible(false);
        fullTimeSelect.setSelected(false);

        
    }//GEN-LAST:event_partTimeSelectMousePressed

    private void fullTimeSelectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullTimeSelectMousePressed
        // TODO add your handling code here:
        hourlyWage.setVisible(false);
        weeksPerYear.setVisible(false);
        hourlyWageBox.setVisible(false);
        weeksPerYearBox.setVisible(false);
        hoursPerWeek.setVisible(false);
        hoursPerWeekBox.setVisible(false);
        partTimeSelect.setSelected(false);
        annualSalary.setVisible(true);
        annualSalaryBox.setVisible(true);
    }//GEN-LAST:event_fullTimeSelectMousePressed

    private void SubmitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMousePressed
        // TODO add your handling code here:
        //create employee using Employee Info       
        
        String fName = firstNameBox.getText();
        String lName = lastNameBox.getText();
        int empNumber = Integer.parseInt(employeeNumber.getText());
        double dRate = Double.parseDouble(deductionRateBox.getText());
        String wLocation = workLocationBox.getText();

        //gender
        if (maleSelected.isSelected() == true){
                gender = "male";
            }
            
            if (femaleSelected.isSelected() == true){
                gender = "female";
            }
            
            if (otherSelected.isSelected() == true){
                gender = "Other";
            }
            
        //work location    
        
            
        if (partTimeSelect.isSelected() == true){
            

        try{
            int hpw = Integer.parseInt(hoursPerWeekBox.getText());   
            double hWage =  Double.parseDouble(hourlyWageBox.getText());
            int wpy = Integer.parseInt(weeksPerYearBox.getText());
                        
            PTEmployee partTimer = new PTEmployee (empNumber, fName, lName, gender, wLocation, dRate, hWage, hpw, wpy);
            this.hashTable.addEmployee(partTimer);
            EmployeeSuccessfullyAdded message = new EmployeeSuccessfullyAdded();
            message.setVisible(true);
            message.setDefaultCloseOperation(EmployeeSuccessfullyAdded.DISPOSE_ON_CLOSE);

            }
        
        catch (NumberFormatException nfe){            
        }
        
        }
        
                              
        else if(fullTimeSelect.isSelected()){
            try{
        
            double anSalary = Double.parseDouble(annualSalaryBox.getText());
            
            
            FTEmployee fullTimer = new FTEmployee (empNumber, fName, lName, gender, wlocation, dRate, anSalary );
            this.hashTable.addEmployee(fullTimer);

            }
        
        catch (NumberFormatException nfe){            
        }
                        
        }

        

        

        
        //Call addToFunction and use employee number as input parameter
        
    }//GEN-LAST:event_SubmitButtonMousePressed

    private void maleSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleSelectedActionPerformed

    private void emplyeeNumberBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emplyeeNumberBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_emplyeeNumberBoxKeyTyped

    private void deductionRateBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deductionRateBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_deductionRateBoxKeyTyped

    private void weeksPerYearBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weeksPerYearBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_weeksPerYearBoxKeyTyped

    private void hoursPerWeekBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoursPerWeekBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_hoursPerWeekBoxKeyTyped

    private void hourlyWageBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hourlyWageBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_hourlyWageBoxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField addEmployeeTitle;
    private javax.swing.JLabel annualSalary;
    private javax.swing.JTextPane annualSalaryBox;
    private javax.swing.JLabel chooseOneOption;
    private javax.swing.JLabel deductionRate;
    private javax.swing.JTextPane deductionRateBox;
    private javax.swing.JLabel employeeNumber;
    private javax.swing.JTextPane emplyeeNumberBox;
    private javax.swing.JCheckBox femaleSelected;
    private javax.swing.JTextPane firstNameBox;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JCheckBox fullTimeSelect;
    private javax.swing.JLabel hourlyWage;
    private javax.swing.JTextPane hourlyWageBox;
    private javax.swing.JLabel hoursPerWeek;
    private javax.swing.JTextPane hoursPerWeekBox;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane9;
    private javax.swing.JTextPane lastNameBox;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JCheckBox maleSelected;
    private javax.swing.JCheckBox otherSelected;
    private javax.swing.JCheckBox partTimeSelect;
    private javax.swing.JLabel weeksPerYear;
    private javax.swing.JTextPane weeksPerYearBox;
    private javax.swing.JLabel workLocation;
    private javax.swing.JTextPane workLocationBox;
    // End of variables declaration//GEN-END:variables
}
