/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ems;

import EmployeeDoesntExist;
import EmployeeSuccessfullyChanged;
import EmployeeSuccessfullyChanged;

/**
 *
 * @author 559544
 */
public class EditEmployee extends javax.swing.JFrame {
    MyHashTable hashTable;
    String gender;
    /**
     * Creates new form EditEmployee
     */
    public EditEmployee(MyHashTable hashTable) {
        this.hashTable = hashTable;
        initComponents();

        editEmployeeTitle.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JLabel();
        maleSelected = new javax.swing.JCheckBox();
        femaleSelected = new javax.swing.JCheckBox();
        otherSelected = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        workLocationBox = new javax.swing.JTextPane();
        hoursPerWeek = new javax.swing.JLabel();
        lastNameText = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        hoursPerWeekBox = new javax.swing.JTextPane();
        workLocation = new javax.swing.JLabel();
        annualSalary = new javax.swing.JLabel();
        fullTimeSelect = new javax.swing.JCheckBox();
        partTimeSelect = new javax.swing.JCheckBox();
        employeeNumber = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        deductionRate = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        deductionRateBox = new javax.swing.JTextPane();
        editEmployeeTitle = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        annualSalaryBox = new javax.swing.JTextPane();
        hourlyWage = new javax.swing.JLabel();
        weeksPerYear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hourlyWageBox = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        weeksPerYearBox = new javax.swing.JTextPane();
        SubmitButton = new javax.swing.JButton();
        chooseOneOption = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lastNameBox = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        firstNameBox = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        employeeNumberBox = new javax.swing.JTextPane();
        enterButton = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNameText.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        firstNameText.setText("First Name");

        maleSelected.setText("Male");
        maleSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleSelectedActionPerformed(evt);
            }
        });

        femaleSelected.setText("Female");

        otherSelected.setText("Other");

        jScrollPane8.setViewportView(workLocationBox);

        hoursPerWeek.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        hoursPerWeek.setText("Hours Per Week");

        lastNameText.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        lastNameText.setText("Last Name");

        hoursPerWeekBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hoursPerWeekBoxKeyTyped(evt);
            }
        });
        jScrollPane12.setViewportView(hoursPerWeekBox);

        workLocation.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        workLocation.setText("Work Location");

        annualSalary.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        annualSalary.setText("Annual Salary");

        fullTimeSelect.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        fullTimeSelect.setText("Full Time");
        fullTimeSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fullTimeSelectMousePressed(evt);
            }
        });

        partTimeSelect.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        partTimeSelect.setText("Part Time");
        partTimeSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                partTimeSelectMousePressed(evt);
            }
        });
        partTimeSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeSelectActionPerformed(evt);
            }
        });

        employeeNumber.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        employeeNumber.setText("Enter Employee Number");

        Gender.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        Gender.setText("Gender");

        deductionRate.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        deductionRate.setText("Deduction Rate");

        deductionRateBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deductionRateBoxKeyTyped(evt);
            }
        });
        jScrollPane11.setViewportView(deductionRateBox);

        editEmployeeTitle.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        editEmployeeTitle.setText("Edit Employee");
        editEmployeeTitle.setBorder(new javax.swing.border.SoftBevelBorder(0));
        editEmployeeTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeTitleActionPerformed(evt);
            }
        });

        annualSalaryBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                annualSalaryBoxKeyTyped(evt);
            }
        });
        jScrollPane13.setViewportView(annualSalaryBox);

        hourlyWage.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        hourlyWage.setText("Hourly Wage");

        weeksPerYear.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        weeksPerYear.setText("Weeks Per Year");

        hourlyWageBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hourlyWageBoxKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(hourlyWageBox);

        weeksPerYearBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weeksPerYearBoxKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(weeksPerYearBox);

        SubmitButton.setText("Submit");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitButtonMousePressed(evt);
            }
        });

        chooseOneOption.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chooseOneOption.setText("Choose One Option");

        jScrollPane2.setViewportView(lastNameBox);

        jScrollPane3.setViewportView(firstNameBox);

        employeeNumberBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeeNumberBoxKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(employeeNumberBox);

        enterButton.setText("Enter");
        enterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(maleSelected)
                        .addGap(18, 18, 18)
                        .addComponent(femaleSelected)
                        .addGap(18, 18, 18)
                        .addComponent(otherSelected))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(Gender))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastNameText)
                                    .addComponent(workLocation)
                                    .addComponent(firstNameText))
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(employeeNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hoursPerWeek)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deductionRate)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(hourlyWage)
                                            .addComponent(annualSalary))
                                        .addComponent(weeksPerYear, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                            .addComponent(jScrollPane11)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enterButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editEmployeeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(partTimeSelect)
                            .addComponent(fullTimeSelect))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chooseOneOption)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editEmployeeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(employeeNumber)))
                .addGap(2, 2, 2)
                .addComponent(chooseOneOption)
                .addGap(18, 18, 18)
                .addComponent(fullTimeSelect)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameText)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(partTimeSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(annualSalary))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hourlyWage)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(workLocation)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Gender)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleSelected)
                            .addComponent(femaleSelected)
                            .addComponent(otherSelected))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hoursPerWeek)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weeksPerYear))
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deductionRate)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleSelectedActionPerformed

    private void fullTimeSelectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullTimeSelectMousePressed
        // TODO add your handling code here:
        hourlyWage.setVisible(false);
        weeksPerYear.setVisible(false);
        hourlyWageBox.setVisible(false);
        weeksPerYearBox.setVisible(false);
        hoursPerWeek.setVisible(false);
        hoursPerWeekBox.setVisible(false);
        partTimeSelect.setSelected(false);
        annualSalary.setVisible(true);
        annualSalaryBox.setVisible(true);
    }//GEN-LAST:event_fullTimeSelectMousePressed

    private void partTimeSelectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partTimeSelectMousePressed
        // TODO add your handling code here:
        hourlyWage.setVisible(true);
        weeksPerYear.setVisible(true);
        hourlyWageBox.setVisible(true);
        weeksPerYearBox.setVisible(true);
        hoursPerWeek.setVisible(true);
        hoursPerWeekBox.setVisible(true);
        annualSalary.setVisible(false);
        annualSalaryBox.setVisible(false);
        fullTimeSelect.setSelected(false);

    }//GEN-LAST:event_partTimeSelectMousePressed

    private void partTimeSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partTimeSelectActionPerformed

    private void editEmployeeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeTitleActionPerformed

    private void SubmitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMousePressed
        // TODO add your handling code here:
        //create employee using Employee Info
        int empNumber = Integer.parseInt(employeeNumberBox.getText());
        
        if(hashTable.isInTable(empNumber) = false){
            EmployeeDoesntExist errorMessage = new EmployeeDoesntExist();
            errorMessage.setVisible(true);
            errorMessage.setDefaultCloseOperation(EmployeeDoesntExist.DISPOSE_ON_CLOSE);
            }
        else{
        

            String fName = firstNameBox.getText();
            String lName = lastNameBox.getText();
            double dRate = Double.parseDouble(deductionRateBox.getText());
            String wLocation = workLocationBox.getText();

            //gender
            if (maleSelected.isSelected() == true){
                gender = "male";
            }

            if (femaleSelected.isSelected() == true){
                gender = "female";
            }

            if (otherSelected.isSelected() == true){
                gender = "Other";
            }

        //work location

            if (partTimeSelect.isSelected() == true){

                try{
                    int hpw = Integer.parseInt(hoursPerWeekBox.getText());
                    double hWage =  Double.parseDouble(hourlyWageBox.getText());
                    int wpy = Integer.parseInt(weeksPerYearBox.getText());

                    PTEmployee partTimer = new PTEmployee (empNumber, fName, lName, gender, wLocation, dRate, hWage, hpw, wpy);
                    this.hashTable.addEmployee(partTimer);
                    EmployeeSuccessfullyChanged message = new EmployeeSuccessfullyChanged();
                    message.setVisible(true);
                    message.setDefaultCloseOperation(EmployeeSuccessfullyChanged.DISPOSE_ON_CLOSE);

                }

                catch (NumberFormatException nfe){
                }

            }

            else if(fullTimeSelect.isSelected()){
                try{

                    double anSalary = Double.parseDouble(annualSalaryBox.getText());

                    FTEmployee fullTimer = new FTEmployee (empNumber, fName, lName, gender, wlocation, dRate, anSalary );
                    this.hashTable.addEmployee(fullTimer);
                    EmployeeSuccessfullyChanged message = new EmployeeSuccessfullyChanged();
                    message.setVisible(true);
                    message.setDefaultCloseOperation(EmployeeSuccessfullyChanged.DISPOSE_ON_CLOSE);

                }

                catch (NumberFormatException nfe){
                }

            }

        //Call addToFunction and use employee number as input parameter

    }//GEN-LAST:event_SubmitButtonMousePressed

    private void enterButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMousePressed
        // TODO add your handling code here:
        int empNumber = Integer.parseInt(employeeNumberBox.getText());
        firstNameBox.setText(this.hashTable.empInfo(empNumber).getFirstName());
        lastNameBox.setText(this.hashTable.empInfo(empNumber).getFirstName());
        workLocationBox.setText(this.hashTable.empInfo(empNumber).getworkLocation());
        deductionRateBox.setText(Double.toString(this.hashTable.empInfo(empNumber).getDeductRate()));
        
        if (hashTable.empInfo(empNumber) instanceof PTemployee){
            partTimeSelect.setSelected(true);
            PTEmployee partTimerEdit = (PTEmployee) this.hashTable.empInfo(employeeNumber);
            hourlyWageBox.setText(Double.toString(partTimerEdit.getHourlyWage()));
            hoursPerWeekBox.setText(Integer.toString(partTimerEdit.getHoursPerWeek()));
            weeksPerYearBox.setText(Integer.toString(partTimerEdit.getWeekPerYear()));
            annualSalaryBox.setText(Double.toString(partTimerEdit.calcAnnualNetIncome(partTimerEdit)));   
        
        
        if (hashTable.empInfo(empNumber) instanceof FTEmployee){
            fullTimeSelect.setSelected(true);
            FTEmployee fullTimerEdit = (FTEmployee) this.hashTable.empInfo(employeeNumber);
            annualSalaryBox.setText(Double.toString(fullTimerEdit.calcAnnualNetIncome(fullTimerEdit)));   
        }
        }
        
        hashTable.removeFromTable(empNumber);
        
    }//GEN-LAST:event_enterButtonMousePressed

    private void employeeNumberBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeNumberBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_employeeNumberBoxKeyTyped

    private void deductionRateBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deductionRateBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_deductionRateBoxKeyTyped

    private void weeksPerYearBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weeksPerYearBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_weeksPerYearBoxKeyTyped

    private void hoursPerWeekBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoursPerWeekBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_hoursPerWeekBoxKeyTyped

    private void hourlyWageBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hourlyWageBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_hourlyWageBoxKeyTyped

    private void annualSalaryBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_annualSalaryBoxKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_annualSalaryBoxKeyTyped

        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel annualSalary;
    private javax.swing.JTextPane annualSalaryBox;
    private javax.swing.JLabel chooseOneOption;
    private javax.swing.JLabel deductionRate;
    private javax.swing.JTextPane deductionRateBox;
    private javax.swing.JTextField editEmployeeTitle;
    private javax.swing.JLabel employeeNumber;
    private javax.swing.JTextPane employeeNumberBox;
    private javax.swing.JButton enterButton;
    private javax.swing.JCheckBox femaleSelected;
    private javax.swing.JTextPane firstNameBox;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JCheckBox fullTimeSelect;
    private javax.swing.JLabel hourlyWage;
    private javax.swing.JTextPane hourlyWageBox;
    private javax.swing.JLabel hoursPerWeek;
    private javax.swing.JTextPane hoursPerWeekBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane lastNameBox;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JCheckBox maleSelected;
    private javax.swing.JCheckBox otherSelected;
    private javax.swing.JCheckBox partTimeSelect;
    private javax.swing.JLabel weeksPerYear;
    private javax.swing.JTextPane weeksPerYearBox;
    private javax.swing.JLabel workLocation;
    private javax.swing.JTextPane workLocationBox;
    // End of variables declaration//GEN-END:variables
}
