//finished
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ems;

/**
 *
 * @author 559544
 */
public class ListAllEmployees extends javax.swing.JFrame {
    MyHashTable hashTable;
    //Main code
    

    /**
     * Creates new form ListAllEmployees
     * @param hashTable
     */
    public ListAllEmployees(MyHashTable hashTable) {
        this.model = (DefaultTableModel) allEmployeesTable.getModel();
        this.hashTable = hashTable;
        initComponents();
        
        

        
        //call display table 
        //create new rows
    }
    DefaultTableModel model;
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        allEmployeesTitle = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        allEmployeesTable = new javax.swing.JTable();
        displayButton = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allEmployeesTitle.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        allEmployeesTitle.setText("All Employees");
        allEmployeesTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        allEmployeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Gender", "Work Location", "Deduction Rate", "Part Time/Full Time", "Annual Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(allEmployeesTable);

        displayButton.setText("Display");
        displayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                displayButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(417, Short.MAX_VALUE)
                .addComponent(allEmployeesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254)
                .addComponent(displayButton)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allEmployeesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayButton))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayButtonMousePressed
        // TODO add your handling code here:
        for (int i = 0; i < hashTable.buckets.length; i++){         

            for (int j = 0; j < hashTable.buckets[i].size(); j++){
                String employeeNumber = Integer.toString(hashTable.buckets[i].get(j).getEmployeeNumber());
                String firstName = hashTable.buckets[i].get(j).getFirstName();
                String lastName = hashTable.buckets[i].get(j).getLastName();
                String deductionRate = Double.toString(hashTable.buckets[i].get(j).getDeductRate());
                String gender = hashTable.buckets[i].get(j).getGender();
                String wLocation = hashTable.buckets[i].get(j).getWorkLocation();

                /*
                if(hashTable.buckets[i].get(j).getGender() == 0){
                    String gender = "Male";
                }

                else if(hashTable.buckets[i].get(j).getGender() == 1){
                    String gender = "Female";
                }

                else if(hashTable.buckets[i].get(j).getGender() == 2){
                    String gender = "Other";
                }

                if(hashTable.buckets[i].get(j).getWorkLocation() == 0){
                    String wLocation = "Mississauga";
                }

                else if(hashTable.buckets[i].get(j).getWorkLocation() == 1){
                    String wLocation = "Toronto";
                }

                else if(hashTable.buckets[i].get(j).getWorkLocation() == 2){
                    String wLocation = "Jungle";
                }
                */

                if(this.hashTable.buckets[i].get(j).getEmployeeNumber instanceof PTEmployee){  
                    String typeWorker = "Part Time";
                    String annualSalary = Double.toString(PTEmployee.calcAnnualNetIncome(hashTable.empInfo(hashTable.buckets.get(j).getEmployeeNumber())));
                    Object[] row = {employeeNumber, firstName,lastName, gender, wLocation,deductionRate, typeWorker, annualSalary };
                    model.addRow(row);
                }    

                if(this.hashTable.buckets[i].get(j).getEmployeeNumber instanceof FTEmployee){  
                    String typeWorker = "Full Time";
                    String annualSalary = Double.toString(FTEmployee.calcAnnualNetIncome(hashTable.empInfo(hashTable.buckets.get(j).getEmployeeNumber())));
                    Object[] row = {employeeNumber, firstName,lastName, gender, wLocation,deductionRate, typeWorker, annualSalary };
                    model.addRow(row);


                }



            }
        }
    }//GEN-LAST:event_displayButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListAllEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListAllEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListAllEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListAllEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListAllEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allEmployeesTable;
    private javax.swing.JTextField allEmployeesTitle;
    private javax.swing.JButton displayButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
